spring.application.name=microservicio-catalogo
spring.datasource.url=jdbc:mysql://localhost:8082/mesatech_db?serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:misa_mesatech}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:h2:mem:catalogodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USERNAME:misa_mesatech}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true