spring.application.name=api-cloud-native

server.port=8080
# Id. de directorio (inquilino)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/ba9c3522-adab-4c57-ac78-dc6131594e07/v2.0

# Desde Exponer API: Ámbitos definidos por esta API
spring.security.oauth2.resourceserver.jwt.audiences=c639b2a3-10c3-4611-b3c8-8acb71c2afc6

# Logging de oauth2 security resource center
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/cloudnative1
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect